### ISSUE TITLE
Add basic tests and coverage tracking + badge

### ISSUE THREAD

**Issue by CodyCBakerPhD** [magland/remfile#1]
I haven't found any issues in trying this out so far, but for officially recommending it to users in lieu of other streaming methods, I'd feel more comfortable knowing I can cite some level of testing that has been performed to ensure the data transfer is performed smoothly

Let me know if you want any help setting up some basic GitHub actions for this

**Comment by magland** [comment]
I have added tests, and there are now three badges including gh action for pytest and codecoverage using codecov.
