### ISSUE TITLE
Expose all global options to user

### ISSUE THREAD

**Issue by CodyCBakerPhD** [magland/remfile#2]
It would be nice if the global options at lines

https://github.com/magland/remfile/blob/main/remfile/RemFile.py#L4-L5

and

https://github.com/magland/remfile/blob/main/remfile/RemFile.py#L110-L111

were exposed to the `__init__` of the `RefFile` class so that a user can easily control them on an instance-to-instance basis

**Comment by magland** [comment]
This is done. There is a note in the docstring that arguments starting with underscore are for experimental purposes only and may experience breaking changes in the future.
