### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by CodyCBakerPhD** [magland/remfile#3]
It would be nice to have thorough docstrings for each method outlining the inputs/outputs and reasoning for design decisions.

Most important for the `RemFile` class (or it's `__init__`) so that someone can ask `RemFile?` and get a helpful description

**Comment by magland** [comment]
This is done.

https://github.com/magland/remfile/blob/e7536b8911f8480c14a7132d4e1930ea843a0fb2/remfile/RemFile.py#L10-L32
